config/routes.rb
Andy::Application.routes.draw do
  resources :works

  resources :collections

  match "past"=>"collections#past"
  get "present"=>"collections#present"
  get "future"=>"collections#future"
  match "about"=>"root#about"
  match "contact"=>"root#contact"

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  attr_accessible :info, :title
  has_many :works
end

app/models/work.rb
class Work < ActiveRecord::Base
  attr_accessible :collection_id, :info, :title, :image
  belongs_to :collection
  has_attached_file :image, :styles=>{:medium=>"300x300>"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @collections }
    end
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    @collection = Collection.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @collection }
    end
  end

  # GET /collections/new
  # GET /collections/new.json
  def new
    @collection = Collection.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @collection }
    end
  end

  # GET /collections/1/edit
  def edit
    @collection = Collection.find(params[:id])
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(params[:collection])

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render json: @collection, status: :created, location: @collection }
      else
        format.html { render action: "new" }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /collections/1
  # PUT /collections/1.json
  def update
    @collection = Collection.find(params[:id])

    respond_to do |format|
      if @collection.update_attributes(params[:collection])
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection = Collection.find(params[:id])
    @collection.destroy

    respond_to do |format|
      format.html { redirect_to collections_url }
      format.json { head :no_content }
    end
  end

  def past
    @works = Collection.find(1).works

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @collections }
    end
  end

  def present
  end

  def future
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
	def about
	end

	def contact
	end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  # GET /works
  # GET /works.json
  def index
    @works = Work.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @works }
    end
  end

  # GET /works/1
  # GET /works/1.json
  def show
    @work = Work.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @work }
    end
  end

  # GET /works/new
  # GET /works/new.json
  def new
    @work = Work.new
    @collections = Collection.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @work }
    end
  end

  # GET /works/1/edit
  def edit
    @work = Work.find(params[:id])
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(params[:work])

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render json: @work, status: :created, location: @work }
      else
        format.html { render action: "new" }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /works/1
  # PUT /works/1.json
  def update
    @work = Work.find(params[:id])

    respond_to do |format|
      if @work.update_attributes(params[:work])
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work = Work.find(params[:id])
    @work.destroy

    respond_to do |format|
      format.html { redirect_to works_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/collections/_form.html.erb
<%= form_for(@collection) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :info %><br />
    <%= f.text_field :info %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collections/about.html.erb
About Andy Tyler

app/views/collections/contact.html.erb
Contact Me for a Good Time

app/views/collections/edit.html.erb
<h1>Editing collection</h1>

<%= render 'form' %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<h1>Collections</h1>

<%= link_to "Past Works", past_path %>
<br>
<%= link_to "Present Works", present_path %>
<br>
<%= link_to "Future Works", future_path %>
<br />
<br>
<%= link_to 'New Collection', new_collection_path %>
<%= link_to 'New Work', new_work_path %>

app/views/collections/new.html.erb
<h1>New collection</h1>

<%= render 'form' %>

<%= link_to 'Back', collections_path %>

app/views/collections/past.html.erb
<h1> Past Works </h1>
<% @works.each do |c| %>
	Title: 
	<%= c.title %>
	<br>
	Info:
	<%= c.info %>
	<br>
	<%= image_tag c.image.url(:medium) if c.image_file_name!=nil%>
	<br>
	<br>
<% end %>

app/views/collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @collection.title %>
</p>

<p>
  <b>Info:</b>
  <%= @collection.info %>
</p>


<%= link_to 'Edit', edit_collection_path(@collection) %> |
<%= link_to 'Back', collections_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Andy</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/works/_form.html.erb
<%= form_for(@work) do |f| %>
  <% if @work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% @work.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :info %><br />
    <%= f.text_field :info %>
  </div>
  <div class="field">
    <%= f.label :collection_id %><br />
    <%=f.select :collection_id, @collections.collect {|i| [i.title,i.id]}%>
  </div>
  <div>
    Image:<br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/works/edit.html.erb
<h1>Editing work</h1>

<%= render 'form' %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

app/views/works/index.html.erb
<h1>Listing works</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Info</th>
    <th>Collection</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @works.each do |work| %>
  <tr>
    <td><%= work.title %></td>
    <td><%= work.info %></td>
    <td><%= work.collection_id %></td>
    <td><%= link_to 'Show', work %></td>
    <td><%= link_to 'Edit', edit_work_path(work) %></td>
    <td><%= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Work', new_work_path %>

app/views/works/new.html.erb
<h1>New work</h1>

<%= render 'form' %>

<%= link_to 'Back', works_path %>

app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @work.title %>
</p>

<p>
  <b>Info:</b>
  <%= @work.info %>
</p>

<p>
  <b>Collection:</b>
  <%= @work.collection_id %>
</p>


<%= link_to 'Edit', edit_work_path(@work) %> |
<%= link_to 'Back', works_path %>